name: FPlugin
main: com.ykn.fplugin.FPlugin
version: 0.0.1
api-version: 1.13
author: ykn

commands:
  f:
    description: Open GUI with various function
    usage: Usage /<command> to open the gui
    permission: fplugin.f
    permission-message: You have no permission to execute this command

permissions:
  fplugin.f:
    default: true
  fplugin.shootmessage:
    default: op
    children:
      fplugin.shootmessage.hitother: true
      fplugin.shootmessage.beinghit: true
      fplugin.shootmessage.all: true
  fplugin.shootmessage.hitother: 
    default: true
  fplugin.shootmessage.beinghit: 
    default: op
  fplugin.shootmessage.all: 
    default: op
  fplugin.deathmessage:
    default: op
    children:
      fplugin.deathmessage.all: true
      fplugin.deathmessage.renamed: true
      fplugin.deathmessage.boss: true
      fplugin.deathmessage.revenge: true
      fplugin.deathmessage.player: true
      fplugin.deathmessage.allplayer: true
  fplugin.deathmessage.all:
    default: op
  fplugin.deathmessage.renamed:
    default: true
  fplugin.deathmessage.boss:
    default: true
  fplugin.deathmessage.revenge:
    default: true
  fplugin.deathmessage.player:
    default: true
  fplugin.deathmessage.allplayer:
    default: op

  