name: FPlugin
main: com.ykn.fplugin.FPlugin
version: 0.0.1
api-version: 1.13
author: ykn

depend: [ProtocolLib]

commands:
  f:
    description: Open GUI with various function
    usage: Usage /<command> to open the gui
    permission: fplugin.f
    permission-message: You have no permission to execute this command

permissions:
  fplugin.f:
    default: true