name: FPlugin
main: com.ykn.fplugin.FPlugin
version: 0.1.0
api-version: 1.13
author: ykn

commands:
  f:
    description: Base command for FMinecraftPlugin
    usage: Type /<command> for more information
    permission: fplugin.f
    permission-message: You do not have permission to execute this command

permissions:
  fplugin.f:
    default: true
  fplugin.command:
    default: op
    children:
      fplugin.command.f: true
      fplugin.command.dev: true
      fplugin.command.reload: true
  fplugin.command.f:
    default: true
  fplugin.command.dev:
    default: op
  fplugin.command.reload:
    default: op
  fplugin.shootmessage:
    default: op
    children:
      fplugin.shootmessage.hitother: true
      fplugin.shootmessage.beinghit: true
      fplugin.shootmessage.all: true
  fplugin.shootmessage.hitother: 
    default: true
  fplugin.shootmessage.beinghit: 
    default: op
  fplugin.shootmessage.all: 
    default: op
  fplugin.deathmessage:
    default: op
    children:
      fplugin.deathmessage.all: true
      fplugin.deathmessage.renamed: true
      fplugin.deathmessage.boss: true
      fplugin.deathmessage.revenge: true
      fplugin.deathmessage.self: true
      fplugin.deathmessage.player: true
  fplugin.deathmessage.all:
    default: op
  fplugin.deathmessage.renamed:
    default: true
  fplugin.deathmessage.boss:
    default: true
  fplugin.deathmessage.revenge:
    default: true
  fplugin.deathmessage.self:
    default: true
  fplugin.deathmessage.player:
    default: op
  fplugin.afk:
    default: op
    children:
      fplugin.afk.bypass: true
      fplugin.afk.inform: true
      fplugin.afk.selfafk: true
      fplugin.afk.allafk: true
      fplugin.afk.selfback: true
      fplugin.afk.allback: true
  fplugin.afk.bypass:
    default: op
  fplugin.afk.inform:
    default: true
  fplugin.afk.selfafk:
    default: true
  fplugin.afk.allafk:
    default: true
  fplugin.afk.selfback:
    default: true
  fplugin.afk.allback:
    default: true
  fplugin.biomemessage:
    default: op
    children: 
      fplugin.biomemessage.self: true
      fplugin.biomemessage.other: true
  fplugin.biomemessage.self:
    default: true
  fplugin.biomemessage.other:
    default: op
  fplugin.siegemessage:
    default: op
    children:
      fplugin.siegemessage.self: true
      fplugin.siegemessage.other: true
  fplugin.siegemessage.self:
    default: true
  fplugin.siegemessage.other:
    default: op
  fplugin.bossmessage:
    default: op
    children:
      fplugin.bossmessage.self: true
      fplugin.bossmessage.other: true
  fplugin.bossmessage.self:
    default: true
  fplugin.bossmessage.other:
    default: op
  